# Numpy - podstawy

* punkt 1
* punkt 2
* ESC, M, Y, B, A, CTRL + ENTER, ALT + ENTER, DD

## olaboga

In [1]:
import numpy as np

In [7]:
x = 6

In [8]:
x

6

In [9]:
x
x**2

36

In [13]:
x = np.array([1,2,3,4,5,6])

In [14]:
x.ndim

1

In [15]:
x.shape

(6,)

In [16]:
x.size

6

In [29]:
A = np.array([[1,2,3],(4,5,6), [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
A.ndim, A.shape, A.size

(2, (3, 3), 9)

## Zmiana kształtu

In [31]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
x.shape = (2,3) # x changes in place!

In [117]:
x[np.newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [37]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
A.reshape(1,9) # returns a new object

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
B = A.reshape(1,9)

In [39]:
B

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
A.reshape(3, -1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Typy i konwersje

In [42]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
x.astype(np.str_)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

In [45]:
np.array([1, 1.23, True, 'Alice']) # see the dtype

array(['1', '1.23', 'True', 'Alice'], dtype='<U32')

In [48]:
np.array([1, True, 1+ 0.j]), np.array([1, True, 1+ 0.j, 'alice'])

(array([1.+0.j, 1.+0.j, 1.+0.j]),
 array(['1', 'True', '(1+0j)', 'alice'], dtype='<U64'))

## Tworzenie wektorów wbudowanymi funkcjami

In [120]:
np.arange(0,10,2)[:,np.newaxis]

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [50]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [52]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [53]:
np.eye(5) # I = identity_matrix = 'eye'

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.diag(np.linspace(1,3,3))

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [54]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### losowanie

In [ ]:
np.random.uniform(-4,4,10) # dziesieć liczb a rozkł. jednostajnego z przed. -4, 4

In [60]:
np.random.uniform(-4,4,(2,5))

array([[ 2.54296483, -0.17740648, -3.38044383, -0.97870581,  3.00293215],
       [ 0.85260741, -2.32505186, -3.98495513, -2.7386205 , -3.73312861]])

In [61]:
np.random.normal(3, 0.1, 10)

array([2.89695142, 3.07295286, 2.97610753, 3.00434119, 2.98569754,
       3.13100391, 2.87133783, 2.9792263 , 3.13110925, 2.98747391])

In [62]:
np.random.normal(3, 0.1, (2,5))

array([[2.93824417, 2.91566403, 2.84776525, 2.96425989, 3.04935601],
       [3.06706525, 3.17866923, 2.98890448, 3.06254372, 3.04439359]])

In [64]:
np.random.randint(2, 5, (2,4)) # bez piątki

array([[4, 4, 4, 4],
       [2, 3, 4, 4]])

In [66]:
np.random.choice([30,32,34], 6, replace=True)

array([32, 30, 34, 30, 34, 34])

In [67]:
np.random.choice([12, 14, 16, 18, 20], 4, replace=False)

array([18, 20, 16, 12])

### tworzenie przez powórzenie

In [68]:
np.repeat(5, 6)

array([5, 5, 5, 5, 5, 5])

In [70]:
np.repeat([1,2], 6)

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

In [71]:
np.repeat([1,2], [2,3])

array([1, 1, 2, 2, 2])

In [73]:
np.tile([1,2], 4)

array([1, 2, 1, 2, 1, 2, 1, 2])

In [74]:
np.tile([1,2], [2,3])

array([[1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2]])

### wstawianie wiersza lub kolumny

In [77]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
np.vstack((A, [100, 99, 98]))

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100,  99,  98]])

In [82]:
np.hstack((A, [[100], [99], [98]]))

array([[  1,   2,   3, 100],
       [  4,   5,   6,  99],
       [  7,   8,   9,  98]])

In [85]:
np.array([1,2,3]).reshape(1,3)

array([[1, 2, 3]])

In [91]:
np.insert(A, 2, [100,99,97], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [100,  99,  97],
       [  7,   8,   9]])

In [92]:
np.insert(A, 2, [100,99,97], axis=1)

array([[  1,   2, 100,   3],
       [  4,   5,  99,   6],
       [  7,   8,  97,   9]])

In [94]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.r_[1, 5,7:11, 99] # łączenie, 'r' stands for 'raw'

array([ 1,  5,  7,  8,  9, 10, 99])

In [98]:
np.r_[1:9:2] # a'la range

array([1, 3, 5, 7])

In [97]:
np.r_[1:10:5j] # !!!!!!!!!!!!!!!!!!!! a'la linspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [102]:
np.c_[1:6:3j, [7,8,9]] # 'c' stands for columns

array([[1. , 7. ],
       [3.5, 8. ],
       [6. , 9. ]])

## Wektoryzacja

In [104]:
np.r_[1,2,4] + np.r_[0,1,3]

array([1, 3, 7])

In [105]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
A = np.arange(12).reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [108]:
A + A

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [110]:
np.r_[1,2,3,4] + np.r_[1,2] # nie działa

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [112]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [111]:
A  * np.r_[1, 10, 100]

array([[   0,   10,  200],
       [   3,   40,  500],
       [   6,   70,  800],
       [   9,  100, 1100]])

In [113]:
raw_factors = np.r_[1, 10 , 100, 1000].reshape(4,1)

In [114]:
raw_factors

array([[   1],
       [  10],
       [ 100],
       [1000]])

In [115]:
A * raw_factors

array([[    0,     1,     2],
       [   30,    40,    50],
       [  600,   700,   800],
       [ 9000, 10000, 11000]])

In [121]:
np.array([True, False]) * np.array([2,3]) # bool to int upcast

array([2, 0])

In [122]:
x = np.r_[1, 4, 6]
y = np.r_[3, 2, 7]
np.minimum(x,y)

array([1, 2, 6])

In [123]:
x <= y

array([ True, False,  True])

In [125]:
1 != np.eye(4)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [126]:
x > 2

array([False,  True,  True])

In [127]:
(x > 2) & (x < 5)

array([False,  True, False])

In [130]:
np.any(x), np.all(x>2) 

(True, False)

In [131]:
np.sum(x > 2)

2

In [132]:
x = np.linspace(0, np.pi, 6)

In [133]:
np.sin(x)

array([0.00000000e+00, 5.87785252e-01, 9.51056516e-01, 9.51056516e-01,
       5.87785252e-01, 1.22464680e-16])

In [134]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [137]:
A.max()

11

In [138]:
A.max(axis = 0)

array([ 9, 10, 11])

In [139]:
A.max(axis = 1)

array([ 2,  5,  8, 11])

## wartosci NaN

In [141]:
nanwek = np.array([1, np.NaN, 3])
nanwek

array([ 1., nan,  3.])

In [142]:
np.sum(nanwek)

nan

In [143]:
np.nansum(nanwek)

4.0

In [144]:
np.sort(nanwek)

array([ 1.,  3., nan])

## indeksowanie, wybór elementów z wektora

In [146]:
x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265])

In [147]:
x[1]

0.6283185307179586

In [149]:
x[1:3]

array([0.62831853, 1.25663706])

In [153]:
x[5:2:-1]

array([3.14159265, 2.51327412, 1.88495559])

In [154]:
x[-2]

2.5132741228718345

In [156]:
x[[-1,1]] # ostatni i pierwszy element w x

array([3.14159265, 0.62831853])

In [162]:
x = np.r_[1,4,6]
x

array([1, 4, 6])

In [160]:
x[[True, False, True]]

array([1, 6])

In [159]:
x[x>2]

array([4, 6])

In [163]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [164]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [166]:
x[::2] = 99
x

array([99,  1, 99,  3, 99,  5, 99,  7, 99,  9, 99, 11, 99, 13, 99, 15, 99,
       17, 99, 19])