In [2]:
import numpy as np

In [85]:
np.random.seed(123)
x = np.random.uniform(-4,4, 30)
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

zad. 1

A)

In [11]:
x[(x >= -2) & (x <= -1) | (x >= 1) & (x <= 2)]

array([ 1.57175348, -1.71088532,  1.75575176,  1.47863791, -1.25457587,
        1.83239766,  1.90396325,  1.07520767,  1.7956426 ,  1.77954706,
       -1.41632869, -1.10569076, -1.65028763,  1.04780899])

B)

In [38]:
np.sum(x[x<=0])

-23.093700684541453

C)

In [17]:
abs(x).mean()

1.5260572308400788

D)

In [18]:
x.min()

-3.522576827123453

In [19]:
x.max()

3.846113587076924

E)

In [50]:
small = abs(x).min()
x[(x==small) | (x == -small)]

array([-0.15254479])

In [49]:
x[np.abs(x).argmin()]

-0.15254478812511252

In [47]:
big = abs(x).max()
x[(x == big) | (x == -big)]

array([3.84611359])

In [48]:
x[np.abs(x).argmax()]

3.846113587076924

F)

In [53]:
x[np.abs(x-2).argmin()]

1.9039632458562856

In [57]:
small = abs(x-2).min()
x[(x-2 == small) | (x-2 == -small)]

array([1.90396325])

In [34]:
big = abs(x-2).max()
x[(x-2 == big) | (x-2 == -big)]

array([-3.52257683])

In [56]:
x[np.abs(x-2).argmax()]

-3.522576827123453

G)

In [55]:
np.modf(x)[0]

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

H)

In [37]:
min_ = x.min()
max_ = x.max()
new_min = -1
new_max = 1
(x - min_) / (max_ - min_) * (new_max - new_min) + new_min

array([ 0.38269625, -0.50827314, -0.63700783,  0.06751533,  0.43263682,
       -0.21086968,  1.        ,  0.35742295, -0.08531046, -0.2781575 ,
       -0.38442224,  0.45343994, -0.17728806, -1.        , -0.26528848,
        0.47286418, -0.73332828, -0.74861452,  0.02460209,  0.02520185,
        0.24792446,  0.71483149,  0.44346393,  0.19716386,  0.4390953 ,
       -0.42832498, -0.34401205, -0.63394237, -0.49182579,  0.24048795])

I)

In [40]:
(x[(x > 3) | (x < -2)] ** 2).mean()

8.315859553206058

K)

In [76]:
y = x.copy().astype(str)
y[x >= 0] = 'nieujemna'
y[x < 0] = 'ujemna'
y

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna'], dtype='<U32')

In [77]:
np.where(x>=0, 'nieujemna', 'ujemna') # broadcasting

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna',
       'ujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'ujemna', 'ujemna',
       'ujemna', 'ujemna', 'nieujemna'], dtype='<U9')

L)

In [81]:
x.sum()/x.size

(-0.01352281479601792, -0.01352281479601792)

M)

In [82]:
( x - x.mean() ) **2

array([ 2.51310095,  2.88103948,  4.71613129,  0.17981074,  3.13033251,
        0.36195325, 14.89679315,  2.22654362,  0.01932711,  0.72171318,
        1.54021269,  3.4074224 ,  0.22838767, 12.31346006,  0.64340154,
        3.67675279,  6.38342126,  6.67118198,  0.07072079,  0.07190094,
        1.18533407,  7.89035273,  3.27307949,  0.81308255,  3.21509958,
        1.96786432,  1.19283081,  4.66720432,  2.67899906,  1.1264252 ])

N)

In [91]:
np.sort(x)[0], np.sort(x)[-1]

(-3.522576827123453, 3.846113587076924)

O)

In [99]:
round(-3.4), -3.4 // 1, np.floor(-3.4)

(-3, -4.0, -4.0)

In [93]:
x // 1 + .5

array([ 1.5, -1.5, -2.5,  0.5,  1.5, -0.5,  3.5,  1.5, -0.5, -0.5, -1.5,
        1.5, -0.5, -3.5, -0.5,  1.5, -2.5, -2.5,  0.5,  0.5,  1.5,  2.5,
        1.5,  0.5,  1.5, -1.5, -1.5, -2.5, -1.5,  1.5])

In [100]:
np.floor(x) + .5

array([ 1.5, -1.5, -2.5,  0.5,  1.5, -0.5,  3.5,  1.5, -0.5, -0.5, -1.5,
        1.5, -0.5, -3.5, -0.5,  1.5, -2.5, -2.5,  0.5,  0.5,  1.5,  2.5,
        1.5,  0.5,  1.5, -1.5, -1.5, -2.5, -1.5,  1.5])

zad. 1.2

In [151]:
def korelacja_1(x, y):
    def sd(x): return np.sqrt(sum((x - x.mean()) ** 2))
    return sum((x - x.mean())*(y - y.mean())) / (sd(x) * sd(y))

def korelacja_2(x,y):
    x_mean = x.mean()
    y_mean = y.mean()
    n = x.size
    numerator = sum(x*y) - n*x_mean*y_mean
    def avgsqr(x): return np.sqrt(sum(x**2) - x.size*x.mean()**2)
    denominator = avgsqr(x) * avgsqr(y)
    return numerator / denominator

In [152]:
x = np.arange(1,11)
y = np.arange(10,0,-1)
korelacja_1(x,y), korelacja_2(x,y)

(-1.0, -1.0)

In [153]:
x = np.random.normal(size=100)
y = 5*x + 2
korelacja_1(x,y), korelacja_2(x,y)

(1.0000000000000002, 0.9999999999999999)

In [154]:
x = np.random.normal(size=100)
y = np.random.normal(size=100)
korelacja(x,y), korelacja(x,y)

(0.07339436284468843, 0.07339436284468843)

zad. 1.3

0.955364996891829

In [137]:
def standarize(x):
    return (x - x.mean()) / np.std(x)

x_std = standarize(x)

In [138]:
x_std.std()

1.0

In [139]:
x_std.mean()

-7.216449660063518e-18

In [146]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
a @ b

array([[ 7, 10],
       [15, 22]])

In [147]:
np.matmul(a, b)

array([[ 7, 10],
       [15, 22]])

In [148]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

zad. 1.4

In [157]:
x * y;

zad. 1.5

In [159]:
def RMSE(x,y):
    n = x.size
    return np.sqrt( sum((y-x) ** 2) / n )

RMSE(x,y)

1.318567310057132

zad. 1.6

In [161]:
def MAE(x,y):
    n = x.size
    return sum(abs(x-y)) / n

MAE(x,y)

1.03585455130962

zad. 1.7

In [164]:
def MedAE(x,y):
    return np.median(abs(x-y))

MedAE(x,y)

0.8256875567205334

zad. 1.8

In [169]:
def Hamming(x,y):
    # print(x != y)
    return sum(x != y) / x.size

Hamming(x,y)

1.0

zad. 1.9

In [191]:
def cross_entropy(y1, y2):
    n = y1.size
    return -sum( y1 * np.log(y2) + (1 - y1)*np.log(1 - y2) ) / n

y1 = np.random.choice((0,1),size=100)
y2 = np.random.uniform(size=100)
cross_entropy(y1, y2)

0.8948473935897135

In [190]:
np.random.choice((0,1), 5)

array([0, 0, 1, 1, 1])

In [229]:
x = np.array([1,4,5,8,12,23])

zad. 1.10

In [224]:
def lead(x,idx):
    return np.r_[x[idx:], [np.NaN]*idx]

lead(x,3)

array([ 8., 12., 23., nan, nan, nan])

In [225]:
def lag(x, idx):
    return np.r_[[np.NaN]*idx, x[:-idx]]


lag(x,2)

array([nan, nan,  1.,  4.,  5.,  8.])

zad. 1.11

In [241]:
x = np.random.choice((True, False), 10)
x

array([ True, False,  True, False,  True, False,  True,  True, False,
        True])

In [257]:
x.argmax()

0

In [256]:
from itertools import accumulate
def cumall(x):
    return np.array(list(accumulate(x, lambda x,y: x and y)))

cumall(x)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [265]:
def cumall_2(x):
    if np.all(x):
        return x.copy()
    idx = x.argmin()
    n = x.size
    return np.r_[np.repeat(True,idx), np.repeat(False, n-idx)]

cumall_2(np.array([True, True]))

array([ True,  True])

In [221]:
from itertools import accumulate
def cumany(x):
    return np.array(list(accumulate(x, lambda x,y: x or y)))

cumany(x)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [268]:
def cumany_2(x):
    if any(~x):
        return x.copy()
    idx = x.argmax()
    n = x.size
    return np.r_[np.repeat(False, n-idx), np.repeat(True, idx)]

cumany_2(np.array([False, False]))

array([False, False])

zad. 1.12

In [269]:
n = 5
x = np.array([6,9,10])
k = x.size
p = np.array([0.1, 0.4, 0.5])

In [288]:
p_cum = np.cumsum(p)
bins = p_cum
bins

array([0.1, 0.5, 1. ])

In [290]:
u = np.random.uniform(size=2)
u

array([0.6336019 , 0.07461217])

In [297]:
x[np.digitize(u, bins)]

array([10,  6])

In [323]:
def losuj(n, x, p):
    bins = np.cumsum(p)
    u = np.random.uniform(size=n)
    return x[np.digitize(u, bins)]

wylosowane = losuj(100, np.array([1,2,3]), np.array([0.1,0.6,0.3]))
wylosowane

array([2, 3, 3, 2, 3, 2, 2, 1, 2, 2, 3, 2, 3, 3, 2, 2, 3, 3, 2, 2, 3, 2,
       2, 2, 3, 3, 1, 2, 2, 3, 3, 3, 1, 2, 2, 2, 3, 2, 3, 3, 3, 2, 2, 2,
       2, 2, 2, 3, 2, 3, 3, 2, 1, 3, 2, 3, 3, 2, 2, 3, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 3, 2, 1, 2, 2, 2, 2, 1,
       1, 2, 3, 3, 2, 2, 2, 3, 1, 2, 1, 2])

In [325]:
np.unique(wylosowane, return_counts=True)[1] / 100

array([0.1 , 0.59, 0.31])

zad. 1.13

In [333]:
x = np.array([1,2,3,4])
y = np.array([5,-2,8,3])
z = np.array([1.5, 2.4, 3.8, 3.9])
idxs = np.digitize(z, x)

In [332]:
y[idxs-1] + (y[idx] - y[idx-1]) * (z - x[idx-1]) / (x[idx] - x[idx-1])

array([  1.5, -11.8, -11.6, -12.3])

In [334]:
def interpolacja_kawalkami(x, y, z):
    idxs = np.digitize(z, x)
    return y[idxs-1] + (y[idx] - y[idx-1]) * (z - x[idx-1]) / (x[idx] - x[idx-1])

interpolacja_kawalkami(x, y, z)

array([  1.5, -11.8, -11.6, -12.3])